### PR TITLE
Fix sendKeys not accepting array as input

### LINKED ISSUE #758: sendKeys on RemoteWebElement no longer accepts an array
### What are you trying to achieve? (Expected behavior)
I'm one of the maintainers of Dusk and we got this issue report just in: https://github.com/laravel/dusk/issues/732 after people started updating to the new 1.8.0 version of php-webdriver. It seems that the changes in https://github.com/php-webdriver/php-webdriver/pull/560 are causing some problems and changing the behavior of some methods. 

For example, we were sending an array of keys to the `sendKeys` but it doesn't accept that anymore when `$this->isW3cCompliant` is set to `true` in `RemoteWebElement`. 

From what I can tell this is set to true automatically based on the driver. The changelog for 1.8.0 notes:

> The protocol will be used automatically when remote end (like Geckodriver, newer Chromedriver etc.) supports it.

This seems unwanted because it changes the behavior (as noted above) on a minor release and thus causes breakages in upstream implementations (like Dusk). 

I'd suggest the automatic enabling of the protocol is reverted and only applied when a new major version is released.

That or the breaking change in this particular case is fixed when the `isW3cCompliant` is enabled. But that would be more work I guess and I don't know where there could be more breaking changes. 

### What do you get instead? (Actual behavior)
Instead of allowing us to pass in an array like before we now get an array to string conversion exception.

### How could the issue be reproduced? (Steps to reproduce)
I don't know the exact code to reproduce with only the php-webdriver but I guess that if you just use the chromedriver and were attempting to pass in an array to `sendKeys` on a `RemoteWebElement` instance before it'll now be broken. There's steps to reproduce the issue with dusk on this issue report: https://github.com/laravel/dusk/issues/732

### Details

* Php-webdriver version: 1.8.0
* PHP version: 7.4.2
* Selenium server version: unknown
* Operating system: unknown
* Browser used + version: unknown

I don't know about the last three versions above. I'll try to ask the person reporting the issue.

### PR DESCRIPTION
**Pull request by OndraM**
Fixes #758

### CODE REVIEW

File: lib/Remote/RemoteKeyboard.php [hunk 1]
```diff
@@ -37,7 +37,7 @@ public function sendKeys($keys)
     {
         if ($this->isW3cCompliant) {
             $activeElement = $this->driver->switchTo()->activeElement();
-            $activeElement->sendKeys($keys);
+            $activeElement->sendKeys(WebDriverKeys::encode($keys, true));
```
Comment (andrewnicols) [inline lib/Remote/RemoteKeyboard.php]: `RemoteWebElement::sendKeys()` is also encoding the values which can lead to a double-encoded value. Strictlly speaking, this doesn't matter because the purpose of `encode` function is largely that of normalisation. The encoded value can be safely re-encoded without any ill effect.

That said, if we were to make changes to `encode` in the future such that it can no longer be called on an already-encoded value, then `sendKeys` would be sending a double-encoded value and this may be difficult to detect.

I'd suggest that we either drop the `encode()` call here entirely (and in the OSS variant too if possible), or we add relevant unit tests to ensure that a value such as the following does not break:

```
$this->driver->getKeyboard()->sendKeys([
    [WebDriverKeys::SHIFT . 'h'],
    'elp',
]);
```

File: lib/WebDriverKeys.php [hunk 2]
```diff
@@ -90,11 +90,13 @@ class WebDriverKeys
...
-     * Encode input of `sendKeys()`.
+     * Encode input of `sendKeys()` to appropriate format according to protocol.
+     *
      * @param string|array|int|float $keys
-     * @return array
+     * @param bool $isW3cCompliant
+     * @return array|string
      */
-    public static function encode($keys)
+    public static function encode($keys, $isW3cCompliant = false)
```
Comment (andrewnicols) [inline lib/WebDriverKeys.php]: For future, we should really rename this to normalise since that it what is happening. No values are encoded.

File: lib/Remote/RemoteKeyboard.php (hunk 1 above)
Comment (OndraM) [reply lib/Remote/RemoteKeyboard.php]: Nice catch, the call is really redundant here and should not be there.

The encode call needs to stay in the OSS version though, because it is not send via `sendKeys()` and it needs to be converted to array of chars (which is the way JsonWire protocol accepts text).

**Comment by lordjancso** [comment]
@OndraM Thank you for the fix! Will you release this patch soon?

**Comment by OndraM** [comment]
@lordjancso I'm also currently taking care of #757 which was introduced in 1.8.0 - so I'd like to release the fix for both of the issues at the same time.

**Comment by lordjancso** [comment]
@OndraM Okay, thank you for the info.
Do you have any ETA of the release or should I lock to 1.7.1? My tests are completely broken with 1.8.0.

**Comment by OndraM** [comment]
Sorry, we generally do not provide any ETAs. But if #757 builds goes well (there is already a pull request with the fix #764), is could be soon.

However you can already add dependency to your composer.json require section: 
```json
"php-webdriver/webdriver": "dev-master as 1.8.1"
```

and start using it right now.
